# CMake generated Testfile for 
# Source directory: /workspace/tests
# Build directory: /workspace/build_fuzz/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_smoke]=] "/workspace/build_fuzz/tests/test_smoke")
set_tests_properties([=[test_smoke]=] PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;21;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_fixed]=] "/workspace/build_fuzz/tests/test_fixed")
set_tests_properties([=[test_fixed]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;25;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_vec2]=] "/workspace/build_fuzz/tests/test_vec2")
set_tests_properties([=[test_vec2]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;26;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_rng]=] "/workspace/build_fuzz/tests/test_rng")
set_tests_properties([=[test_rng]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;27;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_hash]=] "/workspace/build_fuzz/tests/test_hash")
set_tests_properties([=[test_hash]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;28;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_ecs]=] "/workspace/build_fuzz/tests/test_ecs")
set_tests_properties([=[test_ecs]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;29;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_snapshot]=] "/workspace/build_fuzz/tests/test_snapshot")
set_tests_properties([=[test_snapshot]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;30;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_delta]=] "/workspace/build_fuzz/tests/test_delta")
set_tests_properties([=[test_delta]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;31;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_range_coder]=] "/workspace/build_fuzz/tests/test_range_coder")
set_tests_properties([=[test_range_coder]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;32;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_netsim]=] "/workspace/build_fuzz/tests/test_netsim")
set_tests_properties([=[test_netsim]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;33;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_session_rollback]=] "/workspace/build_fuzz/tests/test_session_rollback")
set_tests_properties([=[test_session_rollback]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;34;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_lag_comp]=] "/workspace/build_fuzz/tests/test_lag_comp")
set_tests_properties([=[test_lag_comp]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;35;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_recorder]=] "/workspace/build_fuzz/tests/test_recorder")
set_tests_properties([=[test_recorder]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;36;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_desync]=] "/workspace/build_fuzz/tests/test_desync")
set_tests_properties([=[test_desync]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;37;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_replay_model]=] "/workspace/build_fuzz/tests/test_replay_model")
set_tests_properties([=[test_replay_model]=] PROPERTIES  LABELS "unit" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;10;add_test;/workspace/tests/CMakeLists.txt;38;ironclad_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_udp_transport]=] "/workspace/build_fuzz/tests/test_udp_transport")
set_tests_properties([=[test_udp_transport]=] PROPERTIES  LABELS "network" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;44;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[fuzz_replay_parse]=] "/workspace/build_fuzz/tests/fuzz_replay_parse" "-max_total_time=30" "-print_final_stats=1")
set_tests_properties([=[fuzz_replay_parse]=] PROPERTIES  LABELS "fuzz" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;67;add_test;/workspace/tests/CMakeLists.txt;75;ironclad_add_fuzzer;/workspace/tests/CMakeLists.txt;0;")
add_test([=[fuzz_packet_decode]=] "/workspace/build_fuzz/tests/fuzz_packet_decode" "-max_total_time=30" "-print_final_stats=1")
set_tests_properties([=[fuzz_packet_decode]=] PROPERTIES  LABELS "fuzz" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;67;add_test;/workspace/tests/CMakeLists.txt;76;ironclad_add_fuzzer;/workspace/tests/CMakeLists.txt;0;")
add_test([=[fuzz_range_coder]=] "/workspace/build_fuzz/tests/fuzz_range_coder" "-max_total_time=30" "-print_final_stats=1")
set_tests_properties([=[fuzz_range_coder]=] PROPERTIES  LABELS "fuzz" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;67;add_test;/workspace/tests/CMakeLists.txt;77;ironclad_add_fuzzer;/workspace/tests/CMakeLists.txt;0;")
add_test([=[fuzz_delta_decode]=] "/workspace/build_fuzz/tests/fuzz_delta_decode" "-max_total_time=30" "-print_final_stats=1")
set_tests_properties([=[fuzz_delta_decode]=] PROPERTIES  LABELS "fuzz" TIMEOUT "60" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;67;add_test;/workspace/tests/CMakeLists.txt;78;ironclad_add_fuzzer;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test_soak_smoke]=] "/workspace/build_fuzz/tests/test_soak_smoke")
set_tests_properties([=[test_soak_smoke]=] PROPERTIES  LABELS "soak" TIMEOUT "180" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;92;add_test;/workspace/tests/CMakeLists.txt;0;")
